### ISSUE TITLE
UBSAN issue

### ISSUE THREAD

**Issue by jimhester** [tidyverse/tidyr#1017]
From https://www.stats.ox.ac.uk/pub/bdr/memtests/clang-UBSAN/tidyr/tidyr-Ex.Rout, but posted here for posterity.

```
> # From https://stackoverflow.com/questions/1181060
> stocks <- tibble(
+   time = as.Date('2009-01-01') + 0:9,
+   X = rnorm(10, 0, 1),
+   Y = rnorm(10, 0, 2),
+   Z = rnorm(10, 0, 4)
+ )
> 
> gather(stocks, "stock", "price", -time)
/data/gannet/ripley/R/test-clang/cpp11/include/cpp11/r_vector.hpp:698:24: runtime error: applying non-zero offset 16 to null pointer
    #0 0x7f5e64500fb9 in cpp11::writable::r_vector<cpp11::r_string>::operator[](long) const /data/gannet/ripley/R/test-clang/cpp11/include/cpp11/r_vector.hpp:698:24
    #1 0x7f5e644f9433 in cpp11::writable::r_vector<cpp11::r_string>::operator[](int) const /data/gannet/ripley/R/test-clang/cpp11/include/cpp11/r_vector.hpp:684:10
    #2 0x7f5e644f9433 in melt_dataframe(cpp11::data_frame, cpp11::r_vector<int> const&, cpp11::r_vector<int> const&, cpp11::r_vector<cpp11::r_string>, cpp11::r_vector<cpp11::r_string>, cpp11::sexp, bool, bool, bool) /data/gannet/ripley/R/packages/tests-clang-SAN/tidyr/src/melt.cpp:262:5
    #3 0x7f5e644f10e1 in _tidyr_melt_dataframe /data/gannet/ripley/R/packages/tests-clang-SAN/tidyr/src/cpp11.cpp:24:27
    #4 0x6dfb5d in R_doDotCall /data/gannet/ripley/R/svn/R-devel/src/main/dotcode.c:629:17
    #5 0x72cff1 in do_dotcall /data/gannet/ripley/R/svn/R-devel/src/main/dotcode.c:1281:11
    #6 0x8615f0 in bcEval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:7670:21
    #7 0x826ce9 in Rf_eval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:723:8
    #8 0x88e5bb in R_execClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c
    #9 0x889a17 in Rf_applyClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:1814:16
    #10 0x84a324 in bcEval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:7082:12
    #11 0x826ce9 in Rf_eval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:723:8
    #12 0x88e5bb in R_execClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c
    #13 0x889a17 in Rf_applyClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:1814:16
    #14 0x9b35d4 in dispatchMethod /data/gannet/ripley/R/svn/R-devel/src/main/objects.c:436:16
    #15 0x9b2375 in Rf_usemethod /data/gannet/ripley/R/svn/R-devel/src/main/objects.c:472:10
    #16 0x9b4733 in do_usemethod /data/gannet/ripley/R/svn/R-devel/src/main/objects.c:565:9
    #17 0x844cf6 in bcEval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:7134:15
    #18 0x826ce9 in Rf_eval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:723:8
    #19 0x88e5bb in R_execClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c
    #20 0x889a17 in Rf_applyClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:1814:16
    #21 0x827b22 in Rf_eval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:846:12
    #22 0x95c4a9 in Rf_ReplIteration /data/gannet/ripley/R/svn/R-devel/src/main/main.c:264:2
    #23 0x960910 in R_ReplConsole /data/gannet/ripley/R/svn/R-devel/src/main/main.c:314:11
    #24 0x960739 in run_Rmainloop /data/gannet/ripley/R/svn/R-devel/src/main/main.c:1113:5
    #25 0x960a92 in Rf_mainloop /data/gannet/ripley/R/svn/R-devel/src/main/main.c:1120:5
    #26 0x4dbb2a in main /data/gannet/ripley/R/svn/R-devel/src/main/Rmain.c:29:5
    #27 0x7f5e752d6041 in __libc_start_main (/lib64/libc.so.6+0x27041)
    #28 0x43134d in _start (/data/gannet/ripley/R/R-clang-SAN/bin/exec/R+0x43134d)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /data/gannet/ripley/R/test-clang/cpp11/include/cpp11/r_vector.hpp:698:24 in 
/data/gannet/ripley/R/test-clang/cpp11/include/cpp11/r_vector.hpp:698:24: runtime error: applying non-zero offset 8 to null pointer
    #0 0x7f5e645021de in cpp11::writable::r_vector<SEXPREC*>::operator[](long) const /data/gannet/ripley/R/test-clang/cpp11/include/cpp11/r_vector.hpp:698:24
    #1 0x7f5e644f95e4 in cpp11::writable::r_vector<SEXPREC*>::operator[](int) const /data/gannet/ripley/R/test-clang/cpp11/include/cpp11/r_vector.hpp:684:10
    #2 0x7f5e644f95e4 in melt_dataframe(cpp11::data_frame, cpp11::r_vector<int> const&, cpp11::r_vector<int> const&, cpp11::r_vector<cpp11::r_string>, cpp11::r_vector<cpp11::r_string>, cpp11::sexp, bool, bool, bool) /data/gannet/ripley/R/packages/tests-clang-SAN/tidyr/src/melt.cpp:267:5
    #3 0x7f5e644f10e1 in _tidyr_melt_dataframe /data/gannet/ripley/R/packages/tests-clang-SAN/tidyr/src/cpp11.cpp:24:27
    #4 0x6dfb5d in R_doDotCall /data/gannet/ripley/R/svn/R-devel/src/main/dotcode.c:629:17
    #5 0x72cff1 in do_dotcall /data/gannet/ripley/R/svn/R-devel/src/main/dotcode.c:1281:11
    #6 0x8615f0 in bcEval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:7670:21
    #7 0x826ce9 in Rf_eval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:723:8
    #8 0x88e5bb in R_execClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c
    #9 0x889a17 in Rf_applyClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:1814:16
    #10 0x84a324 in bcEval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:7082:12
    #11 0x826ce9 in Rf_eval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:723:8
    #12 0x88e5bb in R_execClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c
    #13 0x889a17 in Rf_applyClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:1814:16
    #14 0x9b35d4 in dispatchMethod /data/gannet/ripley/R/svn/R-devel/src/main/objects.c:436:16
    #15 0x9b2375 in Rf_usemethod /data/gannet/ripley/R/svn/R-devel/src/main/objects.c:472:10
    #16 0x9b4733 in do_usemethod /data/gannet/ripley/R/svn/R-devel/src/main/objects.c:565:9
    #17 0x844cf6 in bcEval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:7134:15
    #18 0x826ce9 in Rf_eval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:723:8
    #19 0x88e5bb in R_execClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c
    #20 0x889a17 in Rf_applyClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:1814:16
    #21 0x827b22 in Rf_eval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:846:12
    #22 0x95c4a9 in Rf_ReplIteration /data/gannet/ripley/R/svn/R-devel/src/main/main.c:264:2
    #23 0x960910 in R_ReplConsole /data/gannet/ripley/R/svn/R-devel/src/main/main.c:314:11
    #24 0x960739 in run_Rmainloop /data/gannet/ripley/R/svn/R-devel/src/main/main.c:1113:5
    #25 0x960a92 in Rf_mainloop /data/gannet/ripley/R/svn/R-devel/src/main/main.c:1120:5
    #26 0x4dbb2a in main /data/gannet/ripley/R/svn/R-devel/src/main/Rmain.c:29:5
    #27 0x7f5e752d6041 in __libc_start_main (/lib64/libc.so.6+0x27041)
    #28 0x43134d in _start (/data/gannet/ripley/R/R-clang-SAN/bin/exec/R+0x43134d)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /data/gannet/ripley/R/test-clang/cpp11/include/cpp11/r_vector.hpp:698:24 in 
```

**Comment by jimhester** [comment]
Not sure if this is a tidyr or cpp11 issue, but I will try to look into it this week.

**Comment by jimhester** [comment]
I was unfortunately unable to reproduce the error seen, but I am pretty sure I know what the problem is and it should be fixed in the latest cpp11.
